# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks

vscode:
  extensions:
    - almenon.arepl
    - ms-python.python
    - littlefoxteam.vscode-python-test-adapter
    - ms-azuretools.vscode-docker
    - laike9m.cyberbrain
    